---
configuration: "destfile=/home/vcap/jacoco.exec,append=true,includes=*"
serviceBroker:
  planId: 03345e9f-d2a7-4380-b43b-bce61f11121a
  serviceId: 50ea410d-db0c-46fb-b2fb-01999f8bd600
security.user.name: user # login username
security.user.password: user # login password
security.user.role: USER # role assigned to the user
security.require-ssl: false # advanced settings ...
security.enable-csrf: false
security.basic.enabled: true
security.basic.realm: Spring
